name: generate-glb

services:
  generate-glb:
    image: generate-glb
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: ${ACCELERATION:-cpu}  # Default to CPU if not specified
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    environment:
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-all}  # For CUDA builds
    entrypoint: ["python", "src/generate.py"]
